### ISSUE TITLE
后台的搜索按钮有毒

### ISSUE THREAD

**Issue by puresox** [bernardli/ysucsdn#62]
![image](https://cloud.githubusercontent.com/assets/17718921/24864196/fe5856b6-1e35-11e7-9a11-ec7be2251a5c.png)  
1.搜索样式有问题。
2.点邮箱订阅搜索按钮莫名其妙就弹出来了。

**Comment by bernardli** [comment]
！！？？？没见过这个BUG 啊，有空看看
